import React, { useState, useEffect } from "react";
import { useTranslation } from 'react-i18next';
import {
  Search,
  HelpCircle,
  BookOpen,
  MessageCircle,
  Video,
  ChevronRight,
  TrendingUp,
  Zap,
  Shield,
  DollarSign,
  ExternalLink,
  Loader2,
  X,
} from "lucide-react";
import { useTheme } from "../../context/ThemeContext";
import { FeaturePage, FeatureHero, CTABanner } from "../features/FeatureLayout";

// Fallback content if APIs fail
const FALLBACK_ARTICLES = [
  {
    title: "How to Start Trading Cryptocurrency: A Beginner's Guide",
    source: "CoinDesk",
    link: "https://www.coindesk.com/learn/how-to-trade-cryptocurrency-a-beginners-guide/",
    description:
      "Learn the basics of cryptocurrency trading including market analysis, order types, and risk management.",
  },
  {
    title: "Understanding Bitcoin: A Complete Guide",
    source: "Bitcoin.org",
    link: "https://bitcoin.org/en/bitcoin-for-individuals",
    description:
      "Bitcoin is the first decentralized digital currency. This guide explains how it works and how to use it.",
  },
  {
    title: "Crypto Trading Strategies for Beginners",
    source: "Binance Academy",
    link: "https://academy.binance.com/en/articles/crypto-trading-strategies",
    description:
      "Discover proven trading strategies including day trading, swing trading, and HODLing.",
  },
  {
    title: "What is Blockchain?",
    source: "IBM",
    link: "https://www.ibm.com/topics/blockchain",
    description:
      "Blockchain is a shared, immutable ledger that facilitates the process of recording transactions.",
  },
  {
    title: "How to Secure Your Crypto Assets",
    source: "Ledger",
    link: "https://www.ledger.com/academy/security",
    description:
      "Best practices for keeping your cryptocurrency safe from hacks and scams.",
  },
  {
    title: "Technical Analysis Basics",
    source: "TradingView",
    link: "https://www.tradingview.com/education/",
    description:
      "Learn to read charts, identify trends, and use technical indicators.",
  },
];

const FALLBACK_VIDEO = {
  title: "How to Trade on AxionTrade - Complete Beginner's Guide",
  channel: "AxionTrade Official",
  videoId: "d9MyW72ELq0",
  description:
    "Learn how to create an account, deposit funds, and start trading on AxionTrade in this step-by-step tutorial.",
};

// Real FAQ content from common crypto questions
const FAQS = [
  {
    q: "What is the minimum deposit amount?",
    a: "The minimum deposit amount is $10 USD equivalent in cryptocurrency or fiat currency. Bank transfers have a minimum of $50.",
  },
  {
    q: "How long do withdrawals take?",
    a: "Cryptocurrency withdrawals are processed instantly and typically confirmed within 30 minutes. Fiat withdrawals via bank transfer take 1-3 business days.",
  },
  {
    q: "What are the trading fees?",
    a: "Maker fees are 0.08% and taker fees are 0.10%. Fees decrease based on your 30-day trading volume. VIP traders get fees as low as 0.02% maker and 0.04% taker.",
  },
  {
    q: "How do I enable 2FA?",
    a: 'Go to Security Settings, click "Enable Two-Factor Authentication", scan the QR code with Google Authenticator or Authy, and enter the 6-digit code to verify. Keep your backup codes safe.',
  },
  {
    q: "Is AxionTrade regulated?",
    a: "Yes, AxionTrade is registered with FinCEN as a Money Services Business (MSB). We comply with all applicable regulations and maintain licenses in multiple jurisdictions.",
  },
  {
    q: "What cryptocurrencies can I trade?",
    a: "We offer over 200 cryptocurrencies including Bitcoin (BTC), Ethereum (ETH), Solana (SOL), Cardano (ADA), and many more. We regularly add new assets based on community demand.",
  },
  {
    q: "How do I earn staking rewards?",
    a: "Simply deposit supported assets into your Staking wallet. Rewards are distributed automatically based on your holdings and staking duration. No additional steps required.",
  },
  {
    q: "Is there a referral program?",
    a: "Yes! Our referral program offers up to 40% commission on trading fees generated by your referrals. Share your unique referral link and earn passive income.",
  },
];

export default function HelpCenter() {
  const { t } = useTranslation();
  const { darkMode } = useTheme();
  const [searchQuery, setSearchQuery] = useState("");
  const [expandedFaq, setExpandedFaq] = useState(null);
  const [articles, setArticles] = useState([]);
  const [video, setVideo] = useState(null);
  const [loadingArticles, setLoadingArticles] = useState(true);
  const [loadingVideo, setLoadingVideo] = useState(true);
  const [searchResults, setSearchResults] = useState(null);

  // Fetch real articles from RSS feed
  useEffect(() => {
    fetchArticles();
    fetchVideo();
  }, []);

  const fetchArticles = async () => {
    try {
      // Using RSS2JSON to convert RSS feeds to JSON (free, no key)
      const response = await fetch(
        "https://api.rss2json.com/v1/api.json?rss_url=https://cointelegraph.com/rss/tag/bitcoin",
      );
      const data = await response.json();

      if (data.status === "ok" && data.items) {
        const formattedArticles = data.items.slice(0, 8).map((item) => ({
          title: item.title,
          source: "CoinTelegraph",
          link: item.link,
          date: new Date(item.pubDate).toLocaleDateString(),
          description: item.description?.replace(/<[^>]*>/g, "").slice(0, 150),
        }));
        setArticles(formattedArticles);
      } else {
        setArticles(FALLBACK_ARTICLES);
      }
    } catch (err) {
      console.error("Failed to fetch articles:", err);
      setArticles(FALLBACK_ARTICLES);
    } finally {
      setLoadingArticles(false);
    }
  };

  const fetchVideo = async () => {
    try {
      // Using YouTube's free oEmbed API (no key required)
      const videoId = "d9MyW72ELq0"; // AxionTrade tutorial video
      const response = await fetch(
        `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`,
      );
      const data = await response.json();

      setVideo({
        title: data.title,
        channel: data.author_name,
        videoId: videoId,
        thumbnail: data.thumbnail_url,
        description:
          "Learn how to create an account, deposit funds, and start trading on AxionTrade in this step-by-step tutorial.",
      });
    } catch (err) {
      console.error("Failed to fetch video:", err);
      setVideo(FALLBACK_VIDEO);
    } finally {
      setLoadingVideo(false);
    }
  };

  // Handle search - filters both articles and FAQ
  const handleSearch = (query) => {
    setSearchQuery(query);
    if (query.trim() === "") {
      setSearchResults(null);
    } else {
      const filteredArticles = articles.filter(
        (article) =>
          article.title?.toLowerCase().includes(query.toLowerCase()) ||
          article.source?.toLowerCase().includes(query.toLowerCase()) ||
          article.description?.toLowerCase().includes(query.toLowerCase()),
      );

      const filteredFaqs = FAQS.filter(
        (faq) =>
          faq.q.toLowerCase().includes(query.toLowerCase()) ||
          faq.a.toLowerCase().includes(query.toLowerCase()),
      );

      setSearchResults({ articles: filteredArticles, faqs: filteredFaqs });
    }
  };

  const clearSearch = () => {
    setSearchQuery("");
    setSearchResults(null);
  };

  const textClr = darkMode ? "#f1f5f9" : "#0f172a";
  const mutedClr = darkMode ? "#64748b" : "#94a3b8";
  const border = "rgba(245,158,11,0.18)";

  // Display search results if there's a query
  const showSearchResults = searchResults !== null;

  return (
    <FeaturePage>
      <FeatureHero
        badge={t("support_center")}
        title={t("how_can_we_help")}
        highlight={t("help_center")}
        subtitle={t("help_center_subtitle")}
        icon={HelpCircle}
      />

      <div style={{ maxWidth: 1200, margin: "0 auto", padding: "40px 24px 0" }}>
        {/* Search Bar */}
        <div style={{ maxWidth: 600, margin: "0 auto 48px auto" }}>
          <div
            style={{
              display: "flex",
              background: darkMode
                ? "rgba(15,23,42,0.8)"
                : "rgba(248,250,252,0.9)",
              border: `1px solid ${border}`,
              borderRadius: 50,
              padding: "4px 4px 4px 20px",
              alignItems: "center",
            }}
          >
            <Search className="w-5 h-5" style={{ color: mutedClr }} />
            <input
              type="text"
              placeholder={t("search_articles_faqs")}
              value={searchQuery}
              onChange={(e) => handleSearch(e.target.value)}
              style={{
                flex: 1,
                padding: "12px 16px",
                background: "transparent",
                border: "none",
                outline: "none",
                color: textClr,
                fontSize: "1rem",
              }}
            />
            {searchQuery && (
              <button
                onClick={clearSearch}
                style={{
                  padding: "8px",
                  background: "transparent",
                  border: "none",
                  cursor: "pointer",
                }}
              >
                <X className="w-4 h-4" style={{ color: mutedClr }} />
              </button>
            )}
            <button
              onClick={() => handleSearch(searchQuery)}
              className="gold-btn"
              style={{
                padding: "8px 24px",
                borderRadius: 50,
                border: "none",
                cursor: "pointer",
              }}
            >
              {t("search")}
            </button>
          </div>
        </div>

        {/* Search Results */}
        {showSearchResults && (
          <div style={{ marginBottom: 60 }}>
            <div
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                marginBottom: 24,
              }}
            >
              <h2
                style={{
                  fontFamily: '"Playfair Display",serif',
                  fontWeight: 700,
                  fontSize: "1.5rem",
                  color: textClr,
                }}
              >
                {t("search_results_for")} "{searchQuery}"
              </h2>
              <button
                onClick={clearSearch}
                style={{
                  color: mutedClr,
                  fontSize: "0.8rem",
                  background: "transparent",
                  border: "none",
                  cursor: "pointer",
                }}
              >
                {t("clear")}
              </button>
            </div>

            {searchResults.articles.length === 0 &&
            searchResults.faqs.length === 0 ? (
              <div
                style={{
                  textAlign: "center",
                  padding: "40px",
                  background: darkMode
                    ? "rgba(15,23,42,0.6)"
                    : "rgba(248,250,252,0.8)",
                  borderRadius: 20,
                }}
              >
                <p style={{ color: mutedClr }}>
                  {t("no_results_found")} "{searchQuery}". {t("try_different_keywords")}
                </p>
              </div>
            ) : (
              <>
                {/* Search Articles */}
                {searchResults.articles.length > 0 && (
                  <>
                    <h3
                      style={{
                        color: textClr,
                        fontSize: "1.2rem",
                        marginBottom: 16,
                      }}
                    >
                      {t("articles")} ({searchResults.articles.length})
                    </h3>
                    <div
                      style={{
                        display: "grid",
                        gridTemplateColumns:
                          "repeat(auto-fit, minmax(320px, 1fr))",
                        gap: 20,
                        marginBottom: 32,
                      }}
                    >
                      {searchResults.articles.map((article, idx) => (
                        <a
                          key={idx}
                          href={article.link}
                          target="_blank"
                          rel="noopener noreferrer"
                          style={{ textDecoration: "none" }}
                        >
                          <div
                            style={{
                              background: darkMode
                                ? "rgba(15,23,42,0.6)"
                                : "rgba(248,250,252,0.8)",
                              border: `1px solid ${border}`,
                              borderRadius: 20,
                              padding: "20px",
                              transition: "all 0.2s",
                              cursor: "pointer",
                            }}
                            onMouseEnter={(e) =>
                              (e.currentTarget.style.background = darkMode
                                ? "rgba(245,158,11,0.1)"
                                : "rgba(245,158,11,0.05)")
                            }
                          >
                            <div
                              style={{
                                display: "flex",
                                alignItems: "center",
                                justifyContent: "space-between",
                                marginBottom: 12,
                              }}
                            >
                              <span
                                style={{
                                  color: "#f59e0b",
                                  fontSize: "0.7rem",
                                  textTransform: "uppercase",
                                }}
                              >
                                {article.source}
                              </span>
                              {article.date && (
                                <span
                                  style={{
                                    color: mutedClr,
                                    fontSize: "0.7rem",
                                  }}
                                >
                                  {article.date}
                                </span>
                              )}
                            </div>
                            <h3
                              style={{
                                color: textClr,
                                fontSize: "1rem",
                                fontWeight: 600,
                                marginBottom: 8,
                                lineHeight: 1.4,
                              }}
                            >
                              {article.title}
                            </h3>
                            {article.description && (
                              <p
                                style={{
                                  color: mutedClr,
                                  fontSize: "0.8rem",
                                  marginBottom: 12,
                                  lineHeight: 1.5,
                                }}
                              >
                                {article.description}...
                              </p>
                            )}
                            <div
                              style={{
                                color: "#f59e0b",
                                fontSize: "0.8rem",
                                display: "flex",
                                alignItems: "center",
                                gap: 4,
                              }}
                            >
                              {t("read_article")} <ExternalLink className="w-3 h-3" />
                            </div>
                          </div>
                        </a>
                      ))}
                    </div>
                  </>
                )}

                {/* Search FAQs */}
                {searchResults.faqs.length > 0 && (
                  <>
                    <h3
                      style={{
                        color: textClr,
                        fontSize: "1.2rem",
                        marginBottom: 16,
                      }}
                    >
                      {t("faqs")} ({searchResults.faqs.length})
                    </h3>
                    <div style={{ display: "grid", gap: 12 }}>
                      {searchResults.faqs.map((faq, idx) => (
                        <div
                          key={idx}
                          style={{
                            border: `1px solid ${border}`,
                            borderRadius: 12,
                            overflow: "hidden",
                          }}
                        >
                          <button
                            onClick={() =>
                              setExpandedFaq(
                                expandedFaq === `search-${idx}`
                                  ? null
                                  : `search-${idx}`,
                              )
                            }
                            style={{
                              width: "100%",
                              textAlign: "left",
                              padding: "16px 20px",
                              background: darkMode
                                ? "rgba(15,23,42,0.4)"
                                : "rgba(248,250,252,0.6)",
                              border: "none",
                              cursor: "pointer",
                              display: "flex",
                              justifyContent: "space-between",
                              alignItems: "center",
                            }}
                          >
                            <span style={{ color: textClr, fontWeight: 500 }}>
                              {faq.q}
                            </span>
                            <ChevronRight
                              className={`w-4 h-4 transition-transform ${expandedFaq === `search-${idx}` ? "rotate-90" : ""}`}
                              style={{ color: mutedClr }}
                            />
                          </button>
                          {expandedFaq === `search-${idx}` && (
                            <div
                              style={{
                                padding: "16px 20px",
                                background: darkMode
                                  ? "rgba(15,23,42,0.2)"
                                  : "rgba(248,250,252,0.4)",
                                borderTop: `1px solid ${border}`,
                                color: mutedClr,
                                fontSize: "0.9rem",
                              }}
                            >
                              {faq.a}
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </>
                )}
              </>
            )}
          </div>
        )}

        {/* Articles Section - Only show if not searching */}
        {!showSearchResults && (
          <div style={{ marginBottom: 60 }}>
            <h2
              style={{
                fontFamily: '"Playfair Display",serif',
                fontWeight: 700,
                fontSize: "1.8rem",
                color: textClr,
                marginBottom: 24,
              }}
            >
              {t("latest_crypto_guides")}
            </h2>

            {loadingArticles ? (
              <div
                style={{
                  display: "flex",
                  justifyContent: "center",
                  padding: "40px",
                }}
              >
                <Loader2 className="w-8 h-8 text-yellow-500 animate-spin" />
              </div>
            ) : (
              <div
                style={{
                  display: "grid",
                  gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
                  gap: 20,
                }}
              >
                {articles.slice(0, 6).map((article, idx) => (
                  <a
                    key={idx}
                    href={article.link}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{ textDecoration: "none" }}
                  >
                    <div
                      style={{
                        background: darkMode
                          ? "rgba(15,23,42,0.6)"
                          : "rgba(248,250,252,0.8)",
                        border: `1px solid ${border}`,
                        borderRadius: 20,
                        padding: "20px",
                        transition: "all 0.2s",
                        cursor: "pointer",
                        height: "100%",
                      }}
                      onMouseEnter={(e) =>
                        (e.currentTarget.style.background = darkMode
                          ? "rgba(245,158,11,0.1)"
                          : "rgba(245,158,11,0.05)")
                      }
                    >
                      <div
                        style={{
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "space-between",
                          marginBottom: 12,
                        }}
                      >
                        <span
                          style={{
                            color: "#f59e0b",
                            fontSize: "0.7rem",
                            textTransform: "uppercase",
                          }}
                        >
                          {article.source}
                        </span>
                        {article.date && (
                          <span style={{ color: mutedClr, fontSize: "0.7rem" }}>
                            {article.date}
                          </span>
                        )}
                      </div>
                      <h3
                        style={{
                          color: textClr,
                          fontSize: "1rem",
                          fontWeight: 600,
                          marginBottom: 8,
                          lineHeight: 1.4,
                        }}
                      >
                        {article.title}
                      </h3>
                      {article.description && (
                        <p
                          style={{
                            color: mutedClr,
                            fontSize: "0.8rem",
                            marginBottom: 12,
                            lineHeight: 1.5,
                          }}
                        >
                          {article.description}...
                        </p>
                      )}
                      <div
                        style={{
                          color: "#f59e0b",
                          fontSize: "0.8rem",
                          display: "flex",
                          alignItems: "center",
                          gap: 4,
                        }}
                      >
                        {t("read_article")} <ExternalLink className="w-3 h-3" />
                      </div>
                    </div>
                  </a>
                ))}
              </div>
            )}
          </div>
        )}

        {/* FAQ Section - Only show if not searching */}
        {!showSearchResults && (
          <div style={{ marginBottom: 60 }}>
            <h2
              style={{
                fontFamily: '"Playfair Display",serif',
                fontWeight: 700,
                fontSize: "1.8rem",
                color: textClr,
                marginBottom: 24,
              }}
            >
              {t("frequently_asked_questions")}  <span className="gold-text">{t("questions")}</span>
            </h2>
            <div style={{ display: "grid", gap: 12 }}>
              {FAQS.map((faq, idx) => (
                <div
                  key={idx}
                  style={{
                    border: `1px solid ${border}`,
                    borderRadius: 12,
                    overflow: "hidden",
                  }}
                >
                  <button
                    onClick={() =>
                      setExpandedFaq(expandedFaq === idx ? null : idx)
                    }
                    style={{
                      width: "100%",
                      textAlign: "left",
                      padding: "16px 20px",
                      background: darkMode
                        ? "rgba(15,23,42,0.4)"
                        : "rgba(248,250,252,0.6)",
                      border: "none",
                      cursor: "pointer",
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "center",
                    }}
                  >
                    <span style={{ color: textClr, fontWeight: 500 }}>
                      {faq.q}
                    </span>
                    <ChevronRight
                      className={`w-4 h-4 transition-transform ${expandedFaq === idx ? "rotate-90" : ""}`}
                      style={{ color: mutedClr }}
                    />
                  </button>
                  {expandedFaq === idx && (
                    <div
                      style={{
                        padding: "16px 20px",
                        background: darkMode
                          ? "rgba(15,23,42,0.2)"
                          : "rgba(248,250,252,0.4)",
                        borderTop: `1px solid ${border}`,
                        color: mutedClr,
                        fontSize: "0.9rem",
                      }}
                    >
                      {faq.a}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Contact Support */}
        <div
          style={{
            textAlign: "center",
            padding: "40px",
            background: darkMode
              ? "rgba(15,23,42,0.6)"
              : "rgba(248,250,252,0.8)",
            border: `1px solid ${border}`,
            borderRadius: 24,
            marginBottom: 60,
          }}
        >
          <h3
            style={{
              color: textClr,
              fontSize: "1.3rem",
              fontWeight: 600,
              marginBottom: 12,
            }}
          >
            {t("still_need_help_help")}
          </h3>
          <p style={{ color: mutedClr, marginBottom: 20 }}>
            {t("support_team_available")}
          </p>
          <button
            className="gold-btn"
            style={{
              padding: "12px 24px",
              borderRadius: 12,
              border: "none",
              cursor: "pointer",
            }}
          >
            {t("contact_support")}
          </button>
        </div>
      </div>
      <CTABanner
        title={t("start_trading_today_cta")}
        subtitle={t("join_two_million_traders_cta")}
      />
    </FeaturePage>
  );
}